[package]
name = "mcts"
version = "0.1.0"
authors = ["James Harmon <JamesMHarmon@gmail.com>"]
edition = "2018"
publish = false

[lib]
name="mcts"

[dependencies]
failure="0.1"
rand="0.7.0"
rand_distr="0.2.1"
tokio = "=0.2.0-alpha.4"
async-std = "0.99"
futures-preview = "=0.3.0-alpha.18"
generational-arena = "0.2"

engine = { path = "../engine" }
common = { path = "../common" }
model = { path = "../model" }